tap "alienator88/cask"
tap "buo/cask-upgrade"
tap "caskly/tap", "https://github.com/caskly/tap.git"
tap "dail8859/notepadnext"
tap "daniyalmaster693/casks"
tap "domt4/autoupdate"
tap "fastrepl/hyprnote"
tap "felixkratz/formulae"
tap "kennyparsons/gitbak"
tap "knqyf263/pet"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
tap "romankurnovskii/cask"
tap "updatest/tap", "https://github.com/updatest/tap.git"
tap "zimengxiong/tools"
brew "gettext"
brew "xz"
brew "librsvg"
brew "openssl@3"
brew "as-tree"
brew "asimov"
brew "aspell"
brew "autoconf"
brew "automake"
brew "readline"
brew "bat"
brew "sqlite"
brew "bpytop"
brew "cmake"
brew "coreutils"
brew "cpdf"
brew "dav1d"
brew "libb2"
brew "tesseract"
brew "ffmpeg"
brew "gtk4"
brew "libheif"
brew "pkgconf"
brew "czkawka"
brew "direnv"
brew "dua-cli"
brew "enchant"
brew "eza"
brew "fclones"
brew "fd"
brew "fish"
brew "fisher"
brew "libtool"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "htop"
brew "hunspell"
brew "libraw"
brew "imagemagick"
brew "jq"
brew "links"
brew "lua"
brew "luarocks"
brew "mackup"
brew "mailutils"
brew "mas"
brew "micro"
brew "msmtp"
brew "neovim"
brew "node"
brew "ocrmypdf"
brew "pandoc"
brew "php"
brew "pinentry-mac"
brew "pipx"
brew "poppler"
brew "pyenv"
brew "python-setuptools"
brew "python-tk@3.13"
brew "ripgrep"
brew "ripgrep-all"
brew "sevenzip"
brew "shfmt"
brew "speedtest-cli"
brew "starship"
brew "swift"
brew "tcl-tk@8"
brew "thefuck"
brew "tlrc"
brew "topgrade"
brew "tree"
brew "unison"
brew "wget"
brew "xcodegen"
brew "yazi"
brew "zig"
brew "zlib"
brew "zoxide"
brew "zsh"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "felixkratz/formulae/borders"
brew "knqyf263/pet/pet"
cask "1password"
cask "1password-cli"
cask "8x8-work"
cask "alienator88-sentinel"
cask "apparency"
cask "archaeology"
cask "audacity"
cask "betterdisplay"
cask "bloom"
cask "bluesnooze"
cask "brave-browser"
cask "calibre"
cask "caskly@beta"
cask "chatgpt"
cask "claude"
cask "cmake-app"
cask "customshortcuts"
cask "dadroit-json-viewer"
cask "daisydisk"
cask "db-browser-for-sqlite"
cask "deeper"
cask "devonagent"
cask "devonthink"
cask "dhs"
cask "dockdoor"
cask "ente"
cask "fastdmg"
cask "find-any-file"
cask "finicky"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-symbols-only-nerd-font"
cask "github"
cask "github-copilot-for-xcode"
cask "gitkraken-cli"
cask "grammarly-desktop"
cask "hammerspoon"
cask "hazel"
cask "iina"
cask "itermai"
cask "jettison"
cask "karabiner-elements"
cask "keka"
cask "keyboard-maestro"
cask "keycastr"
cask "knockknock"
cask "last-window-quits"
cask "latest"
cask "legcord"
cask "libreoffice"
cask "little-snitch"
cask "lm-studio"
cask "maccy"
cask "macupdater"
cask "microsoft-edge"
cask "neovide-app"
cask "netiquette"
cask "notion"
cask "notunes"
cask "obsidian"
cask "ollama-app"
cask "onyx"
cask "orcaslicer"
cask "orion"
cask "pearcleaner"
cask "pocket-casts"
cask "processspy"
cask "proton-drive"
cask "proton-mail"
cask "proton-mail-bridge"
cask "qspace-pro"
cask "quakenotch"
cask "raindropio"
cask "raspberry-pi-imager"
cask "raycast"
cask "rocket"
cask "script-debugger"
cask "sentinel-app"
cask "setapp"
cask "shortwave"
cask "signal"
cask "silentknight"
cask "skim"
cask "sloth"
cask "soundanchor"
cask "spotify"
cask "startupfolder"
cask "steam"
cask "superkey"
cask "superwhisper"
cask "surfshark"
cask "suspicious-package"
cask "swift-im"
cask "swiftdefaultappsprefpane"
cask "syncthing-app"
cask "syntax-highlight"
cask "taskade"
cask "taskexplorer"
cask "telegram-desktop"
cask "thebrowsercompany-dia"
cask "thelowtechguys-cling"
cask "thetimemachinemechanic"
cask "thumbhost3mf"
cask "todoist-app"
cask "tor-browser"
cask "transnomino"
cask "trezor-suite"
cask "typinator"
cask "updatest@beta"
cask "vlc"
cask "voiceink"
cask "warp"
cask "whatsapp"
cask "xquartz"
mas "1Password for Safari", id: 1569813296
mas "AutoPause", id: 6747332615
mas "Barbee", id: 0
mas "Clean Links", id: 6747395062
mas "CloudMounter", id: 1130254674
mas "Copilot", id: 6738511300
mas "ctrlv", id: 6749192257
mas "Cyclework", id: 6754218094
mas "Developer", id: 640199958
mas "DevHub", id: 6476452351
mas "DS Store Cleaner", id: 6741675455
mas "Find Any File", id: 402569179
mas "Flyleaf", id: 6475200381
mas "Folder Preview", id: 6698876601
mas "Grammarly for Safari", id: 1462114288
mas "Grila", id: 6444335028
mas "Hush", id: 1544743900
mas "Hyperduck", id: 6444667067
mas "JuxtaText", id: 6504801865
mas "Kagi for Safari", id: 1622835804
mas "Kindle", id: 302584613
mas "Markdown Preview", id: 6739955340
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Word", id: 462054704
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Obsidian Web Clipper", id: 6720708363
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Parachute", id: 6748614170
mas "Parcel Classic", id: 639968404
mas "PDFoo", id: 540272061
mas "PDFOutliner", id: 420874236
mas "Peek", id: 1554235898
mas "PiPad", id: 1482575592
mas "PreviewText", id: 1660037028
mas "Raycast Companion", id: 6738274497
mas "rcmd", id: 1596283165
mas "Sandkorn", id: 1377973524
mas "Save to Raindrop.io", id: 1549370672
mas "Save to Reader", id: 1640236961
mas "ScrapNote", id: 6745748946
mas "Shareful", id: 1522267256
mas "SimpleLogin for Safari", id: 6475835429
mas "Spokenly", id: 6740315592
mas "Startup Manager", id: 1296723195
mas "Stickier", id: 6447073047
mas "Super Agent", id: 1568262835
mas "TestFlight", id: 899247664
mas "Text Toolset", id: 1157225201
mas "TextMine/ Text to Data", id: 0
mas "TextPlus", id: 1234445803
mas "uBlock Origin Lite", id: 6745342698
mas "Userscripts", id: 1463298887
mas "WakeMinder", id: 6744974871
mas "Wayback Machine", id: 1472432422
mas "Xcode", id: 497799835
mas "XSpeak", id: 6748146688
mas "YABA", id: 6747272081
vscode "actboy168.extension-path"
vscode "anthropic.claude-code"
vscode "bladnman.auto-align"
vscode "carlocardella.vscode-texttoolbox"
vscode "charliermarsh.ruff"
vscode "continue.continue"
vscode "cppcxy.emmylua-codestyle"
vscode "davidanson.vscode-markdownlint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "google.geminicodeassist"
vscode "idleberg.applescript"
vscode "ionutvmi.path-autocomplete"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.mypy-type-checker"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cpptools-themes"
vscode "openai.chatgpt"
vscode "qcz.text-power-tools"
vscode "sumneko.lua"
vscode "swiftlang.swift-vscode"
vscode "tamasfe.even-better-toml"
vscode "upstash.context7-mcp"
vscode "vadimcn.vscode-lldb"
vscode "virgilsisoe.hammerspoon"
vscode "virgilsisoe.hammerspoon-snippets"
vscode "zainchen.json"
go "github.com/sammcj/gollama"
