#!/bin/sh

dockutil --no-restart --remove all
dockutil --no-restart --add "/Applications/QSpace Pro.app"
dockutil --no-restart --add "/Applications/Visual Studio Code - Insiders.app"
dockutil --no-restart --add "/Applications/OctoApp.app"
dockutil --no-restart --add "/Applications/OrcaSlicer.app"
dockutil --no-restart --add "/Applications/Dia.app"
dockutil --no-restart --add "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app"
dockutil --no-restart --add "/Applications/8x8 Work.app"
dockutil --no-restart --add "/System/Applications/Messages.app"
dockutil --no-restart --add "/Applications/Shortwave.app"
dockutil --no-restart --add "/Applications/Proton Mail.app"
dockutil --no-restart --add "/Applications/Microsoft Outlook.app"
dockutil --no-restart --add "/Applications/Microsoft Teams.app"
dockutil --no-restart --add "/Applications/Recall.app"
dockutil --no-restart --add "/Applications/Setapp/Antinote.app"
dockutil --no-restart --add "/Applications/Shadow.app"
dockutil --no-restart --add "/Applications/ChatGPT.app"
dockutil --no-restart --add "/Applications/Hyperlink.app"
dockutil --no-restart --add "/Applications/Skim.app"
dockutil --no-restart --add "/Applications/"
dockutil --no-restart --add "~/Downloads"
dockutil --no-restart --add "~/Library/CloudStorage/OneDrive-Personal/"
