"use strict";var B=Object.create;var y=Object.defineProperty;var D=Object.getOwnPropertyDescriptor;var Q=Object.getOwnPropertyNames;var W=Object.getPrototypeOf,F=Object.prototype.hasOwnProperty;var N=(t,e)=>{for(var n in e)y(t,n,{get:e[n],enumerable:!0})},E=(t,e,n,o)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of Q(e))!F.call(t,r)&&r!==n&&y(t,r,{get:()=>e[r],enumerable:!(o=D(e,r))||o.enumerable});return t};var O=(t,e,n)=>(n=t!=null?B(W(t)):{},E(e||!t||!t.__esModule?y(n,"default",{value:t,enumerable:!0}):n,t)),R=t=>E(y({},"__esModule",{value:!0}),t);var G={};N(G,{default:()=>b});module.exports=R(G);var i=require("@raycast/api"),a=require("react"),C=require("node:child_process"),P=O(require("node:path")),A=require("node:fs"),T=require("node:fs/promises"),s=require("react/jsx-runtime");function j(){let t="qalc.cfg",e=P.default.join(i.environment.supportPath,t);try{(0,A.accessSync)(e)}catch{let n=P.default.join(i.environment.assetsPath,t);(0,A.copyFileSync)(n,e)}}async function H(){let t=P.default.join(i.environment.supportPath,"qalc.history");try{let e=await(0,T.readFile)(t,{encoding:"utf-8"}),n=[];for(let o of e.split(`
`))o&&n.push([o,"\u2015 "]);return n.reverse()}catch{return[]}}function v(t,e,n,o,r=[]){let l=(0,C.spawn)(t[0],[],{env:{...process.env,QALCULATE_USER_DIR:i.environment.supportPath}});l.on("error",c=>{r.push([t[0],c]),!o[0]&&t.length>1?v(t.slice(1),e,n,o,r):n(r)}),o[0]?l.stdin.end():e(l)}function J(t){t=t.replaceAll(/\x1B\[[0-9]+(;[0-9]+)?m/g,"").replaceAll("\x1B[0J","").replaceAll(/\x1B\[[0-9]+[AG]/g,"");let e=[],n=0;for(let o of t.split(`
`)){if(!o||o.trim()===">")continue;let r=0;for(let u=0;u<o.length;u++){let m=o[u];m==="("?n++:m===")"?n=Math.max(0,n-1):n==0&&(m==="="||m==="\u2248")&&(e.push(o.slice(r,u)),r=u)}let l=o.slice(r),c=l.trim();l&&c!=="="&&c!=="\u2248"&&e.push(l)}return e.length==0&&e.push(""),e}function M(t){let e=(0,a.useRef)(t);return(0,a.useEffect)(()=>{e.current=t},[t]),e.current}var q="\u23F3";function b(){let[t,e]=(0,a.useState)(0);return(0,s.jsx)(U,{rerender:()=>e(t+1)},t)}function U(t){let e=(0,i.getPreferenceValues)(),[n,o]=(0,a.useState)(void 0),[r,l]=(0,a.useState)(""),c=M(r),[u,m]=(0,a.useState)({a:[],loading:!0}),[w,k]=(0,a.useState)(!1),h=(0,a.useRef)({a:[],loading:!0});function L(f){let d=f.toString("utf-8");if(d==="\x1B[0J")return;let g=J(d),p=g[g.length-1];p&&h.current.a.length&&h.current.a[0][1]===q&&(h.current.a[0][1]=p),m({a:g,loading:!1})}function I(){r.trim().length>0&&h.current.a.unshift([r,q]),n?.stdin?.write("\b".repeat(r.length)+r+`
`)}if((0,a.useEffect)(()=>{let f=[e.qalcPath,e.qalcPathText,e.qalcPathText+(e.qalcPathText.endsWith("/")?"qalc":"/qalc")],d=[0],g=()=>d[0]=1;return j(),H().then(p=>{h.current.loading&&(h.current.loading=!1,h.current.a=[...h.current.a,...p])}),v(f,p=>{p.stdout.on("data",L),o(p),g=()=>p.stdin.end()},k,d),()=>g()},[]),(0,a.useEffect)(()=>{n?.stdin?.writable&&(r.length>c.length&&r.startsWith(c)?n.stdin.write(r.slice(c.length)):r.length<c.length&&c.startsWith(r)?n.stdin.write("\b".repeat(c.length-r.length)):n.stdin.write("\b".repeat(c.length)+r))},[r,n]),w)return V(w,t.rerender);let x=(0,s.jsx)(i.Action,{title:"Execute",shortcut:{modifiers:["alt"],key:"enter"},onAction:I}),S=r.trim()==="",_=S&&h.current.a.length===0;return(0,s.jsx)(i.List,{isLoading:u.loading,searchText:r,onSearchTextChange:l,searchBarPlaceholder:"Qalc anything...",children:_?(0,s.jsx)(i.List.EmptyView,{title:"Start typing a calculation"}):(0,s.jsxs)(s.Fragment,{children:[S?(0,s.jsx)(s.Fragment,{}):(0,s.jsx)(i.List.Section,{title:u.a[0],children:u.a.length>1?u.a.slice(1).map((f,d)=>(0,s.jsx)(i.List.Item,{title:f,actions:(0,s.jsxs)(i.ActionPanel,{children:[(0,s.jsx)(i.Action.CopyToClipboard,{title:"Copy",content:f.slice(2),shortcut:{modifiers:["cmd"],key:"."}}),x]})},d)):(0,s.jsx)(i.List.Item,{title:"Execute to see the result",actions:(0,s.jsx)(i.ActionPanel,{children:x})},-1)}),(0,s.jsx)(i.List.Section,{title:"History",children:h.current.a.map(([f,d],g)=>(0,s.jsx)(i.List.Item,{title:f,accessories:[{text:d}],actions:(0,s.jsxs)(i.ActionPanel,{children:[(0,s.jsx)(i.Action,{title:"Replace Input",onAction:()=>l(f)}),x]})},g))})]})})}function V(t,e){return(0,s.jsx)(i.Detail,{markdown:`Hello!
---
I cannot find \`qalc\` on your machine. Please help!

If you have \`qalc\` installed, you can find it by running \`which qalc\`. Please copy that path into the settings.

You can get \`qalc\` from [https://qalculate.github.io/downloads.html](https://qalculate.github.io/downloads.html)  
or homebrew \`brew install libqalculate\`
 
---
Places checked:      _EACCES - permission denied (\`chmod +x\`), ENOENT - no such path_
${t.map(([n,o])=>"- "+n+`  
`+o).join(`
`)}
---
Press \`Enter\` to open settings or \`Alt\` \`Enter\` to try searching again.
`,actions:(0,s.jsxs)(i.ActionPanel,{children:[(0,s.jsx)(i.Action,{title:"Open Settings",onAction:i.openExtensionPreferences}),(0,s.jsx)(i.Action,{title:"Try Again!",shortcut:{modifiers:["alt"],key:"enter"},onAction:e})]})})}
